services:
    mongodb:
        build:
            context: ./backend
            dockerfile: Dockerfile.mongodb
        container_name: mongodb
        ports:
            - '27017:27017'
        volumes:
            - mongodb_data:/data/db
        networks:
            - app-network

    mongo-express:
        image: mongo-express:latest
        container_name: mongo-express
        ports:
            - '8081:8081'
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=password
            - ME_CONFIG_MONGODB_SERVER=mongodb
        depends_on:
            - mongodb
        networks:
            - app-network

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile.api
        container_name: backend-api
        ports:
            - '8000:8000'
        volumes:
            - ./backend:/app
        environment:
            - MONGODB_URL=mongodb:27017
            - MONGODB_USERNAME=root
            - MONGODB_PASSWORD=password
            - MONGODB_DATABASE=blogdumoderateur
        depends_on:
            - mongodb
        networks:
            - app-network

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: frontend-react
        ports:
            - '5173:5173'
        volumes:
            - ./frontend:/app
            - /app/node_modules
        environment:
            - VITE_API_URL=http://localhost:8000
        depends_on:
            - backend
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    mongodb_data:
